name: Publish to GitHub Package Registry (npm.pkg.github.com)
on:
  release:
    types: [created]

jobs:
  publish-npm-pkg-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPOSITORY_TOKEN }}

      - name: ðŸ“¦ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com

      - name: ðŸ“ Reemplazar package.json con package.github.json
        run: cp package.github.json package.json

      - name: ðŸ“¦ Extraer versiÃ³n de package.github.json
        run: |
          VERSION=$(jq -r .version package.github.json)
          echo "La versiÃ³n extraÃ­da es: $VERSION"
          # Establecer la versiÃ³n como una variable de entorno para el siguiente paso
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - run: npm ci

      - run: npm publish --tag $VERSION
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}